version: '3.9'
services:
  db_postgres:
    image: 'postgres:alpine'
    container_name: pg-user-service-container
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5442:5432'
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

  app:
    image: bruslanb/app-user-service-image:1.0.1 # use image from docker hub
    container_name: app-user-service-container
    user: '1001:1001' # specify the UID and GID of the user you want to run the container as
    depends_on:
      db_postgres:
        condition: service_healthy
    environment:
      - SERVER_PORT=8080
    ports:
      - '8080:8080'