server:
  port: 8080

spring:
  application:
    name: UserService

  datasource:
#    url: jdbc:postgresql://localhost:5432/user_db
    url: jdbc:postgresql://db_postgres:5432/user_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  flyway:
    locations: classpath:db/migration
    enabled: true
    clean-disabled: false
    baseline-on-migrate: true
